# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on:
  pull_request:
    paths:
      - '**.php'
  push:
    branches:
      - "master"
    paths:
      - '**.php'

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          extensions: mbstring

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: "lowest"

      -  name: Write secret to file
         run: |
           cat << EOF > ./config/sheet.json
           ${{ secrets.CREDENTIALS }}
           EOF

      - name: "Tests"
        run: "./vendor/phpunit/phpunit/phpunit --no-configuration ./tests"